// Runnable lifecycle check for the disposable browser model, not SSH behavior.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
for (const [, script] of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)) new vm.Script(script);
const context = vm.createContext({ structuredClone });
vm.runInContext(html.match(/<script id="model">([\s\S]*?)<\/script>/)[1], context);
let state = context.initial();
const act = (action, value) => state = context.reduce(state, action, value);
const connection = () => state.connections[0];
act('shell'); act('manage'); act('shell'); act('manage');
act('transfer'); act('run', 'Local tool using master socket');
for (let i = 0; i < 12; i++) act('tick');
assert.equal(connection().shells.length, 2);
assert.ok(connection().shells.every(shell => shell.ticks === 12 && shell.lines.length === 8 && shell.discarded > 0));
assert.equal(connection().transfer.bytes, 100);
assert.equal(connection().run.status, 'COMPLETE');
act('resume', 1); assert.equal(state.active, 1);
act('quit'); act('relaunch');
assert.equal(connection().shells.length, 0);
assert.equal(connection().status, 'CONNECTED');
assert.equal(connection().tunnels.length, 1);
act('transfer'); act('run', 'Remote command'); act('lost');
assert.equal(connection().transfer.status, 'INTERRUPTED');
assert.equal(connection().run.status, 'INTERRUPTED');
act('shell'); assert.equal(connection().shells.length, 0);
act('connect'); assert.equal(connection().status, 'CONNECTING');
act('tick'); assert.equal(connection().status, 'CONNECTING');
act('connected'); assert.equal(connection().tunnels.length, 0);
act('shell'); act('close');
assert.equal(connection().shells.length, 0);
assert.equal(connection().status, 'DISCONNECTED');
assert.equal(state.connections[1].status, 'DISCONNECTED');
console.log('Interaction model: background activity, bounds, quit/close, loss and explicit reconnect passed.');
