load("@rules_go//go:def.bzl", "go_library", "go_test")
go_library(
    name = "launch",
    srcs = ["activity.go", "audit.go", "files_linux.go", "package.go", "daemon_linux.go", "operations_linux.go", "trace.go"],
    importpath = "github.com/Bochner/burrow/core/launch",
    visibility = ["//visibility:public"],
    deps = ["@org_golang_x_sys//unix"],
)

go_test(
    name = "digest_test",
    srcs = ["digest_test.go", "rpc_test.go"],
    embed = [":launch"],
)

go_test(
    name = "online_test",
    srcs = ["online_test.go"],
    deps = [":launch"],
    args = ["-wheel", "$(location @hovel_linux_wheel//file)"],
    data = ["@hovel_linux_wheel//file"],
    tags = ["no-sandbox"],
)

go_test(
    name = "hovel_wal_test",
    srcs = ["online_test.go"],
    deps = [":launch"],
    args = ["-wheel", "$(location @hovel_linux_wheel//file)", "-check-wal-lock"],
    data = ["@hovel_linux_wheel//file"],
    tags = ["no-sandbox", "hovel-followup"],
)

go_test(
 name = "audit_test",
 srcs = ["audit_test.go"],
 tags = ["no-sandbox"],
 deps = [":launch"],
)
